theme: jekyll-theme-minimal
title: "CODE Marketing Cloud" Quickstart Guide
description: "CODE Marketing Cloud" Quickstart Guide
logo: /images/f_logo.png
show_downloads: false
google_analytics: UA-37027461-5
site:
  github:
    is_project_page: false
    is_user_page: false
absolute_url: /ja/
